### ISSUE TITLE
Failed to build bgs

### ISSUE THREAD

**Issue by nikfloydrose** [andrewssobral/bgslibrary#24]
Hello,
I am using Ubuntu 14.04 with opencv-3.0.0-rc1 libraries correctly installed.
I am trying to build the latest branch of bgslibrary (bgslibrary-opencv3) but when i run the make command i get the following error:

nico@nico-pc:~/Downloads/bgslibrary-opencv3/build$ make
Scanning dependencies of target bgs
[  1%] Building CXX object CMakeFiles/bgs.dir/FrameProcessor.cpp.o
[  2%] Building CXX object CMakeFiles/bgs.dir/PreProcessor.cpp.o
[  3%] Building CXX object CMakeFiles/bgs.dir/VideoAnalysis.cpp.o
[  4%] Building CXX object CMakeFiles/bgs.dir/VideoCapture.cpp.o
[  5%] Building CXX object CMakeFiles/bgs.dir/package_bgs/pl/LBSP.cpp.o
[  6%] Building CXX object CMakeFiles/bgs.dir/package_bgs/pl/SuBSENSE.cpp.o
In file included from /home/nico/Downloads/bgslibrary-opencv3/package_bgs/pl/BackgroundSubtractorSuBSENSE.h:3:0,
                 from /home/nico/Downloads/bgslibrary-opencv3/package_bgs/pl/SuBSENSE.cpp:2:
/home/nico/Downloads/bgslibrary-opencv3/package_bgs/pl/BackgroundSubtractorLBSP.h:29:10: error: ‘AlgorithmInfo’ in namespace ‘cv’ does not name a type
  virtual cv::AlgorithmInfo* info() const;
          ^
/home/nico/Downloads/bgslibrary-opencv3/package_bgs/pl/BackgroundSubtractorLBSP.h:23:15: warning: ‘virtual void BackgroundSubtractorLBSP::initialize(const cv::Mat&)’ was hidden [-Woverloaded-virtual]
  virtual void initialize(const cv::Mat& oInitImg);
               ^
In file included from /home/nico/Downloads/bgslibrary-opencv3/package_bgs/pl/SuBSENSE.cpp:2:0:
/home/nico/Downloads/bgslibrary-opencv3/package_bgs/pl/BackgroundSubtractorSuBSENSE.h:41:15: warning:   by ‘virtual void BackgroundSubtractorSuBSENSE::initialize(const cv::Mat&, const cv::Mat&)’ [-Woverloaded-virtual]
  virtual void initialize(const cv::Mat& oInitImg, const cv::Mat& oROI);
               ^
make[2]: *** [CMakeFiles/bgs.dir/package_bgs/pl/SuBSENSE.cpp.o] Error 1
make[1]: *** [CMakeFiles/bgs.dir/all] Error 2
make: *** [all] Error 2 

I really don't get the point of the error: can anybody help me please?
Thanks

**Comment by andrewssobral** [comment]
Hi @nikfloydrose sorry for my delayed response. I will check this problem and I will let you updated asap.

**Comment by skormel** [comment]
Hi,

I've got a similar compilation error, with the opencv3 branch:

Here is the output.

Scanning dependencies of target bgs
[  1%] Building CXX object CMakeFiles/bgs.dir/FrameProcessor.cpp.o
[  2%] Building CXX object CMakeFiles/bgs.dir/PreProcessor.cpp.o
[  3%] Building CXX object CMakeFiles/bgs.dir/VideoAnalysis.cpp.o
[  4%] Building CXX object CMakeFiles/bgs.dir/VideoCapture.cpp.o
[  5%] Building CXX object CMakeFiles/bgs.dir/package_bgs/WeightedMovingVarianceBGS.cpp.o
[  6%] Building CXX object CMakeFiles/bgs.dir/package_bgs/pl/BackgroundSubtractorLBSP.cpp.o
In file included from /home/adelgado/Descargas/bgslibrary-opencv3/package_bgs/pl/BackgroundSubtractorLBSP.cpp:1:0:
/home/adelgado/Descargas/bgslibrary-opencv3/package_bgs/pl/BackgroundSubtractorLBSP.h:29:14: error: ‘AlgorithmInfo’ in namespace ‘cv’ does not name a type
  virtual cv::AlgorithmInfo* info() const;
              ^
/home/adelgado/Descargas/bgslibrary-opencv3/package_bgs/pl/BackgroundSubtractorLBSP.cpp:47:5: error: ‘AlgorithmInfo’ in namespace ‘cv’ does not name a type
 cv::AlgorithmInfo* BackgroundSubtractorLBSP::info() const {
     ^
CMakeFiles/bgs.dir/build.make:169: recipe for target 'CMakeFiles/bgs.dir/package_bgs/pl/BackgroundSubtractorLBSP.cpp.o' failed
make[2]: *** [CMakeFiles/bgs.dir/package_bgs/pl/BackgroundSubtractorLBSP.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/bgs.dir/all' failed
make[1]: *** [CMakeFiles/bgs.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2


Is there any solution?

**Comment by Mona77** [comment]
Hi,

I have OS X Yosemite 10.10.3, and opecv2.4.11. I got similar error to @skormel, please help us to resolve the issue.

Thanks.

**Comment by andrewssobral** [comment]
Hello guys! @nikfloydrose @skormel @Mona77 
sorry for my late response.
I fixed the branch opencv3, now it works great in my Ubuntu 14.04 with OpenCV 3.0 final.
Please, let me know if it is working for you.
Best

**Comment by Mona77** [comment]
Hi Andrew,

Is it possible to fix the master brach as well, because I have Opencv 2.4 ?

**Comment by andrewssobral** [comment]
Hi @Mona77, I fixed the BackgroundSubtractorLBSP class, please let me know if it works now for you.

**Comment by Achal104** [comment]
Hi,
I am using windows 10 and have Anaconda 4.2 and python 2.7.12 with opencv version 2.4.13
I am trying to build bsglibrary, but every time i try doing it it gives the following:
Collecting BGSLibrary
  Using cached bgslibrary-2.0.0.tar.gz
Requirement already satisfied: numpy in c:\users\satish chandra\anaconda2\lib\site-packages (from BGSLibrary)
Building wheels for collected packages: BGSLibrary
  Running setup.py bdist_wheel for BGSLibrary ... error
  Complete output from command "c:\users\satish chandra\anaconda2\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\satish~1\\appdata\\local\\temp\\pip-build-u1qmg2\\BGSLibrary\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\satish~1\appdata\local\temp\tmpz4boeqpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_ext
  building 'libbgs' extension
  error: Unable to find vcvarsall.bat

  ----------------------------------------
  Failed building wheel for BGSLibrary
  Running setup.py clean for BGSLibrary
Failed to build BGSLibrary
Installing collected packages: BGSLibrary
  Running setup.py install for BGSLibrary ... error
    Complete output from command "c:\users\satish chandra\anaconda2\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\satish~1\\appdata\\local\\temp\\pip-build-u1qmg2\\BGSLibrary\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\satish~1\appdata\local\temp\pip-2ro1jm-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'libbgs' extension
    error: Unable to find vcvarsall.bat

I also tried installing Visual Studio 2013 but it didnt solve my problem. When i tried building the wheels for bsglibrary it gave the following error:

Collecting BGSLibrary
  Using cached bgslibrary-2.0.0.tar.gz
Collecting numpy (from BGSLibrary)
  Downloading numpy-1.14.2-cp27-none-win_amd64.whl (13.3MB)
    100% |################################| 13.3MB 50kB/s
  Saved c:\users\satish chandra\numpy-1.14.2-cp27-none-win_amd64.whl
Skipping numpy, due to already being wheel.
Building wheels for collected packages: BGSLibrary
  Running setup.py bdist_wheel for BGSLibrary ... error
  Complete output from command "c:\users\satish chandra\anaconda2\python.exe" -u -c "import setuptools, tokenize;__file__='c:\\users\\satish~1\\appdata\\local\\temp\\pip-build-liwtx3\\BGSLibrary\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\satish~1\appdata\local\temp\tmpqwanigpip-wheel-:
  running bdist_wheel
  running build
  running build_ext
  building 'libbgs' extension
  error: Unable to find vcvarsall.bat

  ----------------------------------------
  Failed building wheel for BGSLibrary
  Running setup.py clean for BGSLibrary
Failed to build BGSLibrary
ERROR: Failed to build one or more wheels.

I dont know what wrong i am doing. I have kind of tried every method that i can find on net.
I even tried using the methods written on the following site:
https://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat

I totally dont know how to fix it anymore. Can you please guide me?
Thank you
